version: "3.9"
services:
  pc12-cis:
    build: .
    ports:
      - "8787:8787"
    environment:
      - ROOT=TRUE
      - PASSWORD=pwd
      - DISABLE_AUTH=true
    volumes:
      - .:/home/rstudio
